# Generated by Django 5.0.4 on 2024-04-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_discipline', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=255)),
                ('semester_discipline', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '1,2')], max_length=50)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.discipline')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.speciality')),
            ],
        ),
    ]
